server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/actions-study
    username: study
    password: study

logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
