name: "github actions"

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    # gradlew 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Start-Actions
      run: CI_PLAT=test-actions make test-github

#  image-push:
#    runs-on: ubuntu-latest
    #- name: Test with Gradle
    #  run: ./gradlew --info test
