name: "github actions"

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    # gradlew 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
  start-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: start-Container
      run: CI_FLAG=test-actions make -f ./MakeFile start-container

  end-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: terminate-Container
        run: CI_FLAG=test-actions make -f ./MakeFile terminate-container


#  image-push:
#    runs-on: ubuntu-latest
    #- name: Test with Gradle
    #  run: ./gradlew --info test
